dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.82
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.82
- name: medbo-backend
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.4
- name: medbo-hack
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: medbo-portals
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
